### ISSUE TITLE
Some data is not collected/presented

### ISSUE THREAD

**Issue by emikolajczak** [RocketChat/Rocket.Chat.Metrics#3]
Hi, first of all it is very good tool, interesting statistics, nice presentation :)
I have noticed that some of statistics are not collected/presented in Grafana.
This empty graphs are:
- Metrics Size
- Metrics Requests
- GC - Seconds Running
- GC - Bytes Freed
- Limit by type
- Limit by method
- Limit by UserId
- Limit by connectionId
- Push Queue
- Meteor Facts

Could you check and explain?

**Comment by frdmn** [comment]
Hi @emikolajczak! Which version of Rocket.Chat are you running currently? 

The first four (Metrics Size, Metrics Requests, GC - Seconds Running and GC - Seconds Freed) were introduced by version 3.1.0 (by PR RocketChat/Rocket.Chat#17183). 

The next four (DDP related ones), are probably only recording metrics if you are actually using the DDP Limiter within Rocket.Chat.

Last but not least, the Push Queue and Meteor facts should have been also added since 3.1.0 (by PR RocketChat/Rocket.Chat#17216 and RocketChat/Rocket.Chat#17208). So if you are not yet on that version, it would explain why some of them are missing for you.
